### ISSUE TITLE
Prepare for production

### ISSUE THREAD

**Issue by lopis** [ReDI-School/job-board#1]
The project needs to be prepared for production. This means that build scripts need to be setup so the code is ready to be deployed.
For now, we can simply have a static web page that connects to the API. This will even allow us to use free hosting like Github Pages.

**Comment by kimamov** [comment]
I tried running a github action for deployment but looks like there is build script (adding react-scripts build didn't help).
Maybe someone else feels like adding it don't feel to confident messing with the config.

**Comment by lopis** [comment]
I'm a bit shocked... our app even minimized exceeds 2MB. Could it be because of MaterialUI?

**Comment by lopis** [comment]
![image](https://user-images.githubusercontent.com/2715751/114316361-7e3bfd80-9b03-11eb-9733-8529ab8031c1.png)

Ho...ly... cow.... 

Supposedly there should be some tree shaking going on, but clearly that's not working correctly.

**Comment by kimamov** [comment]
> I'm a bit shocked... our app even minimized exceeds 2MB. Could it be because of MaterialUI?

same code with standard create-react-app typescript preset gives me 1.25mb without any optimisations.
Not good either but its good for prototyping.
We really don't need to use stuff like Box, Container etc but I think we can fix that later

**Comment by lopis** [comment]
I managed to make it quite a bit better by importing only each necessary icon and component. So this:

```
import { Publish } from '@material-ui/icons';
```

becomes this:

```
import PublishIcon from '@material-ui/icons/Publish';
```

The bundle went _down to 200KB_. I did not use create-react-app exactly because I hate this sort of hidden stuff.

**Comment by kimamov** [comment]
> I managed to make it quite a bit better by importing only each necessary icon and component. So this:
> 
> ```
> import { Publish } from '@material-ui/icons';
> ```
> 
> becomes this:
> 
> ```
> import PublishIcon from '@material-ui/icons/Publish';
> ```
> 
> The bundle went _down to 200KB_. I did not use create-react-app exactly because I hate this sort of hidden stuff.

Nice! its weird tho. even material ui docs say it should work out of the box with named imports...

**Comment by lopis** [comment]
Exactly, I was reading the same. Maybe I'm doing something wrong, but for now I created an ESLint rule to force this style of imports lol
