### ISSUE TITLE
Connect to the actual API

### ISSUE THREAD

**Issue by lopis** [ReDI-School/job-board#3]
Once the API backend exists, connect to it and remove the mocks (including from webpack config)

**Comment by kimamov** [comment]
Think I might just start up a [json-server](https://github.com/typicode/json-server) until they figure out the backend

**Comment by lopis** [comment]
Where would you run it? We could also simply copy the mocks over in production for now 🤷🏼

**Comment by kimamov** [comment]
ya that would be the easiest solution :) but otherwise on one of my vps can't be sitting almost idle forever
